server:
  port: 8082
spring:
  application:
    name: MOVIE-SERVICE
    
  datasource:
    url: jdbc:postgresql://localhost:5432/Show-Ease
    username: postgres
    password: root
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
       format_sql: true